### ISSUE TITLE
Updating permissions... on start is a problem on large installations

### ISSUE THREAD

**Issue by lexxxel** [Wonderfall/docker-nextcloud#14]
I do have more then 4 million files on my instance. A restart with this, otherwise nice, image takes over half an hour. If one could disable the permissions check with a environment variable, it would be beautiful ;-)

All It would take would be an additional check before line 21 in docker-nextcloud/rootfs/usr/local/bin/run.sh

**Comment by benyanke** [comment]
I'd work on this if I knew it would get merged...right now it seems this repo and image is as good as abandoned - please ping me if you see action on here and I'll write it up for ya as a PR

**Comment by benyanke** [comment]
@lexxxel give my fork a look - this is implemented.

https://github.com/benyanke/docker-nextcloud

**Comment by DanielYWoo** [comment]
+1

**Comment by Wonderfall** [comment]
Sorry I didn't get in touch in time. Support for legacy images has ended since they're now obsolete: consider using the new image instead or the official image. Have a nice day!

(As for your issue, it's a known one due to terrible chown performance on the `overlay2` storage driver used by default in Docker. The new image doesn't enforce that anymore.)
