### ISSUE TITLE
chown is slow, we just need it once for the first start-up

### ISSUE THREAD

**Issue by DanielYWoo** [Wonderfall/docker-nextcloud#32]
In run.sh we find any mismatched files and update the permission accordingly. This is necessary if you change the uid/gid, that's good, but that's is very slow.

```
echo "Updating permissions..."
for dir in /nextcloud /data /config /apps2 /var/log /php /nginx /tmp /etc/s6.d; do
  if $(find $dir ! -user $UID -o ! -group $GID|egrep '.' -q); then
    echo "Updating permissions in $dir..."
    chown -R $UID:$GID $dir
```

I think we need to:
1) print a message "for the first boot it might take 10 minutes to finish" to tell the impatient users to wait.
2) write a flag and skip the check next time if the container is restarted.
What do you think?

**Comment by DanielYWoo** [comment]
I don't want a flag for this, I want it mandatory for the first run, then never do it again

**Comment by benyanke** [comment]
I would accept Apple request on my fork which implements another flag that could enable this feature.

**Comment by Wonderfall** [comment]
Sorry I didn't get in touch in time. Support for legacy images has ended since they're now obsolete: consider using the new image instead or the official image. Have a nice day!

(As for your issue, it's a known one due to terrible chown performance on the overlay2 storage driver used by default in Docker. The new image doesn't enforce that anymore.)
