### ISSUE TITLE
Not running as root?

### ISSUE THREAD

**Issue by ryannix123** [Wonderfall/docker-nextcloud#72]
Hello,

I went to deploy your image in OpenShift 3.11, however, I'm getting an error that the image is actually running as root. Any idea why that might be the case?

`Image wonderfall/nextcloud runs as the root user which might not be permitted by your cluster administrator.`

**Comment by Wonderfall** [comment]
[The boot script](https://github.com/Wonderfall/docker-nextcloud/blob/master/rootfs/usr/local/bin/run.sh) itself is running as `root` as it is needed to set permissions.
Once it's done the container should not be using `root` anymore.

So it seems your setup is detecting and restricting the usage of `root` (which is a good thing, tbh), hence the container cannot start since it needs it to start.

**Comment by ryannix123** [comment]
I agree it's a good security practice not to run a container as root. OpenShift requires non-privileged users to run containers as non-root. Maybe I'll fork your Docker file and try to use Redhat's UBI8 instead.

**Comment by Wonderfall** [comment]
The new image is 100% unprivileged, so I think I can close the issue!
