### ISSUE TITLE
Exit code 132 when starting the container / AVX instructions in hardened malloc

### ISSUE THREAD

**Issue by Lochnair** [Wonderfall/docker-nextcloud#82]
Hey man, thanks for the great image!

I've been having some trouble upgrading to the new refactored image tonight, it keeps restarting with exit code 132.

I did some digging and found that if I run the container with `-e LD_PRELOAD=""` it starts up fine.

In addition changing from `image: ghcr.io/wonderfall/nextcloud` to `build: ./docker-nextcloud` to build the image locally on the host it also runs fine.

Managed to get a crashdump from it, it crashes on the vmovdqa instruction. Looking that up it's an AVX instruction, the poor old [G3220 CPU](https://ark.intel.com/content/www/us/en/ark/products/77773/intel-pentium-processor-g3220-3m-cache-3-00-ghz.html) I run Nextcloud on doesn't support that.

```
(gdb) display/i $pc
1: x/i $pc
=> 0x7f456d22bc80 <chacha_keysetup>:    vmovdqa 0x49a8(%rip),%xmm0        # 0x7f456d230630
(gdb)
```

Per the readme for hardened malloc:

> CONFIG_NATIVE: true (default) or false to control whether the code is optimized for the detected CPU on the host. If this is disabled, setting up a custom -march higher than the baseline architecture is highly recommended due to substantial performance benefits for this code.

So by default it's compiled with native code which is bad news for guys like me with old CPU's. I'm not sure if there's a suitable march setting that allows it to run on older CPU's, but still doesn't remove all the performance benefits of native code.

**Comment by Wonderfall** [comment]
Hey, sorry the issues. It's funny since I was about to open an issue about it since I noticed some weird issues about it related to illegal instructions on some CPUs.

I'm going to take a deeper look this week. Perhaps I should drop hardened_malloc altogether or made it optional, although the benefit it provides is real and I suggest using it whenever possible.

**Comment by Lochnair** [comment]
Thanks for the reply :)

Hehe, I'll admit I was kinda surprised no-one had run into this by now, but tbf I'm probably not the only one that didn't notice the image moving to GitHub.

Personally I'd prefer you keep it as I like the features it provides. You could compile it with `-march=x86_64` to make it run everywhere and let users choose whether to use it with an environment variable.

Of course it's also possible to compile multiple binaries targeting different CPU's and selecting the right library based on CPU flags on startup, but that might not be worth the extra maintenance burden.

**Comment by Wonderfall** [comment]
Okay, so I think we should compile hardened_malloc with `CONFIG_NATIVE` set to `false`. Otherwise it will build using [whatever native means](https://github.com/GrapheneOS/hardened_malloc/blob/main/Makefile#L42) for the GitHub servers, so a set of instructions we can't control - usually only supported by modern CPUs.

Default behavior would then be `-march=x86_64` which is the generic set of instructions provided by `x86_64`. I could raise the level beyond the generic one but I'm not sure of the repercussions. For now, I think we can take the tradeoff: it's better if the distributed image run than not at all. I made it so one can set `CONFIG_NATIVE` to whatever they like at build-time, so if they feel  like they need the optimization of `native`, they can build themselves to get that.

**Comment by Wonderfall** [comment]
I'll keep this issue open for now to evaluate this change. :)

**Comment by Wonderfall** [comment]
So far it seems good to me, I didn't notice anything suspicious on my machines since the change. We'll keep it that way now, and users who want faster code can still build themselves. I'll close this for now.

**Comment by Lochnair** [comment]
@Wonderfall Thanks! Realized I'd have to build it myself due to using a different UID/GID pair, so I might as well compile with native :)
