### ISSUE TITLE
502 Bad Gateway on nginx-proxy

### ISSUE THREAD

**Issue by rgarcia89** [Wonderfall/docker-nextcloud#83]
I am using the nginx reverse proxy form https://github.com/nginx-proxy/nginx-proxy which was working with the old image version pretty fine so far. Today I tried to migrate to the new version. 

When I try to start that one I get a `502 Bad Gateway` from my reverse nginx proxy.
In the config I can see the server as beeing shown as down
```
upstream nextcloud.domain.de {
                                ## Can be connected with "bridge" network
                # nextcloud
                        server 10.0.3.7 down;
}
```

Looking into docker everything looks fine - also the pod logs look fine.
```
6824da3c615c   ghcr.io/wonderfall/nextcloud:21.0.2      "docker-php-entrypoi…"   20 hours ago    Up 36 minutes   0.0.0.0:8888->8888/tcp, 9000/tcp           nextcloud
```
```
Starting code integrity check...
Finished code integrity check
Update successful
Turned off maintenance mode
Resetting log level
Nextcloud is already latest version
```

Am I missing some change?
I have tried to login directly using the localhost:8888.
Doing so I am directed to the login prompt. However the login freezes when trying to login.

**Comment by Wonderfall** [comment]
Hello. You didn't miss anything, reverse proxy settings shouldn't change. On the previous image, HSTS was disabled a while ago (it should be set by the reverse proxy instead), so that's the only "recent" thing that should've been updated that comes to my mind. I can't help with the specifics regarding nginx-proxy since I use Traefik myself.

Some things you could try and check:
- Make sure you have set your reverse proxy container in the `trusted_proxies` array in `config.php`
- Did you follow the other [migration steps](https://github.com/Wonderfall/docker-nextcloud#migration-from-the-legacy-image) as well?
- What interesting entries from nginx logs can you get? Same for Nextcloud (`/data/nextcloud.log`)
- Last ressort: try to build the image yourself, and/or try disabling hardened malloc (`LD_PRELOAD=""`)

**Comment by Wonderfall** [comment]
Closing as the issue wasn't updated for a while, feel free to re-open if this is still a problem. Also, proxy examples will be provided sometime soon.
