### ISSUE TITLE
PHP Deprecated

### ISSUE THREAD

**Issue by DeAlexPesh** [Wonderfall/docker-nextcloud#85]
PHP Deprecated:  Required parameter $tagManager follows optional parameter $fileIdentifier in /nextcloud/apps/files/lib/Helper.php on line 220

**Comment by Wonderfall** [comment]
These kinds of errors in the logs are to be expected since the compatibility with PHP 8 is not quite there yet.
The PHP version of the image itself is not deprecated, in fact it's the latest available (8.x).

If you have some issues with PHP 8, you can build the image with PHP 7.4 fairly easily by using a build-time argument like the following command (can be adapted to a docker-compose too):

```
docker build --build-arg PHP_VERSION=7.4 -t wonderfall/nextcloud https://github.com/Wonderfall/docker-nextcloud
```

It will then proceed to build the image with the latest PHP 7.4.x version available, which is fully supported by Nextcloud 21. Hope this was helpful.
