### ISSUE TITLE
Add imagick for php8

### ISSUE THREAD

**Issue by DRON4eg** [Wonderfall/docker-nextcloud#89]
imagick 3.5.0 PHP 8.0 support
imagick 3.5.1 last version
need to install these packages...
add line in dockerfile:
```
 && apk add -t build-deps \
        ...
        imagemagick-dev \
```
and
```
&& apk --no-cache add \
        ...
        imagemagick \
```
```
pecl install imagick \
docker-php-ext-enable imagick \
```

**profit...**

**Comment by Wonderfall** [comment]
`imagick` not being bundled by default is a choice, since it adds a tremendous attack surface while adding very little to the experience (or so I think). Official Nextcloud image makes the same choice if I recall correctly.

In the future there will be instructions like these to get it work for those who want it!

**Comment by DRON4eg** [comment]
@Wonderfall 
Well, in the admin panel nextcloud (v22.1.0) swears at the lack of imagick and recommends installing it.
I actually decided to install it, previously it was impossible.

**Comment by DRON4eg** [comment]
@Wonderfall 
Understood thanks)
